google:
    analytics:
        enhanced_ecommerce: false
        session_auto_started: true
        trackers:
            default:
                #name: MyJavaScriptCompatibleVariableNameWithNoSpaces
                accountId: %google_analytics_id%
                domain: %domaine%
                setSiteSpeedSampleRate: 5
                allowAnchor: true
                allowHash: true
                includeNamePrefix: false
                plugins:
                    - 'linkid'
        whitelist: [ 'q', 'utm_source', 'utm_medium', 'utm_term', 'utm_content', 'utm_campaign' ]
