<?php

namespace Manudev\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Manudev\UserBundle\Entity\User;

/**
 * GiftRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BankAccountRepository extends EntityRepository
{


     public function findForUserQueryBuilder(User $user)
     {
         $query = $this->createQueryBuilder('ba')
             ->where('ba.user = :user')
             ->setParameter('user', $user)
         ;

         return $query;
     }

     public function findForUser(Lists $entity) {
         return $this->findForUserQueryBuilder($entity)->getQuery()->getResult();
     }
}
