<?php

namespace KDO\Bundle\KDOBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ListsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ListsRepository extends EntityRepository
{

    public function listOfUser($user) {
        $query = $this->createQueryBuilder('list')
            ->join('list.users', 'u', 'WITH', 'u.id = :userId')
            ->setParameter('userId', $user->getId())
            ->getQuery();

        return $query->getResult();
    }
}
