<?php

namespace KDO\Bundle\KDOBundle\Repository;

use Doctrine\ORM\EntityRepository;
use KDO\Bundle\KDOBundle\Entity\User;

/**
 * ListsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ListsRepository extends EntityRepository
{

    public function listForUserQueryBuilder(User $user, $withSubList = NULL)
    {
        $query = $this->createQueryBuilder('list')
            ->join('list.users', 'u', 'WITH', 'u.id = :userId')
            ->setParameter('userId', $user->getId())
        ;

        if (!$withSubList) {
            $query->where('list.parent is NULL');
        }
        return $query;
    }

    public function listForUser(User $user, $withSubList = NULL) {
        return $this->listForUserQueryBuilder($user, $withSubList)->getQuery()->getResult();
    }
}
