<?php

namespace KDO\Bundle\KDOBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ListOwnerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ListOwnerRepository extends EntityRepository
{
}
