hwi_oauth:
    connect:
        confirmation: true
        #account_connector: my_user_provider
        account_connector: hwi_oauth.user.provider.fosub_bridge
        #registration_form_handler: hwi_oauth.registration.form.handler.fosub_bridge
        #registration_form: fos_user.registration.form

    firewall_name: main

    fosub:
        username_iterations: 30
        properties:
            # these properties will be used/redefined later in the custom FOSUBUserProvider service.
            google: google_id
            facebook: facebook_id
            windows_live: windows_live_id

    resource_owners:
        google:
            type:                google
            client_id:           %google_id%
            client_secret:       %google_secret%
            scope:               "https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile"

        facebook:
            type:                facebook
            client_id:           %facebook_id%
            client_secret:       %facebook_secret%

        windows_live:
            type:                windows_live
            client_id:           %windows_live_id%
            client_secret:       %windows_live_secret%
            scope:               "wl.basic wl.signin"
