<?php

namespace Manudev\KDOBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * GiftReservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GiftReservationRepository extends EntityRepository
{
}
