<?php

namespace Manudev\KDOBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * GiftReservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GiftReservationRepository extends EntityRepository
{

    public function cleanReservationsQueryBuilder(Lists $list)
    {
        $query = $this->createQueryBuilder();

        //$query->delete('GiftReservation', 'gr');
        if ($list == null) {
            // TODO clean  all
        } else {
            // clean for gift
            //$query->andWhere($qb->expr()->eq('gr.project', ':project'));
            //$query->setParameter(':project', $list);

        }
        return $query;
    }

    public function cleanReservations(Lists $list) {
        return $this->cleanReservationsQueryBuilder($list)->getQuery()->execute();
    }
}
