
# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [MopaBootstrapBundle]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        less:
            node: /usr/local/bin/node
            node_paths: [/usr/local/lib/node_modules]
            apply_to: "\.less$"
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        yui_css:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor.jar"
        yui_js:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor.jar"
    assets:
        fontawesome_css:
            inputs:
                - %kernel.root_dir%/../web/bundles/manudevcore/bower/fontawesome/less/font-awesome.less
            filters:
                - less
                - cssrewrite
            output: css/fontawesome.css

        font-awesome-otf:
            inputs: '%kernel.root_dir%/../web/bundles/manudevcore/bower/fontawesome/fonts/FontAwesome.otf'
            output: 'fonts/FontAwesome.otf'
        font-awesome-eot:
            inputs: '%kernel.root_dir%/../web/bundles/manudevcore/bower/fontawesome/fonts/fontawesome-webfont.eot'
            output: 'fonts/fontawesome-webfont.eot'
        font-awesome-svg:
            inputs: '%kernel.root_dir%/../web/bundles/manudevcore/bower/fontawesome/fonts/fontawesome-webfont.svg'
            output: 'fonts/fontawesome-webfont.svg'
        font-awesome-ttf:
            inputs: '%kernel.root_dir%/../web/bundles/manudevcore/bower/fontawesome/fonts/fontawesome-webfont.ttf'
            output: 'fonts/fontawesome-webfont.ttf'
        font-awesome-woff:
            inputs: '%kernel.root_dir%/../web/bundles/manudevcore/bower/fontawesome/fonts/fontawesome-webfont.woff'
            output: 'fonts/fontawesome-webfont.woff'
