<?php

namespace Manudev\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * KdoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
}
