<?php

namespace Manudev\KDOBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Manudev\KDOBundle\Entity\GiftReservation;

/**
 * GiftReservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GiftReservationRepository extends EntityRepository
{

    /**
     * Delete all Reservation older than 2 days and where status is reserved.
     * @return mixed Query
     */
    public function cleanReservationsQueryBuilder()
    {
        $twoDaysAgo = new \DateTime();
        $twoDaysAgo->modify("-2 days");

        $query = $this->createQueryBuilder('gr');

        $query->delete('Manudev\KDOBundle\Entity\GiftReservation', 'gr');
        $query->andWhere($query->expr()->lte('gr.created', ':created'));
        $query->andWhere($query->expr()->eq('gr.status', ':status'));
        $query->setParameter('created', $twoDaysAgo);
        $query->setParameter('status', GiftReservation::STATUS_RESERVED);

        return $query;
    }

    public function cleanReservations() {
        return $this->cleanReservationsQueryBuilder()->getQuery()->execute();
    }
}
